apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ytoh
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0028-tenant/tkrw-pr712-0075-0028-app/devfile-sample-ytoh@sha256:0ce5524af60cc1d7760ede442464f09ec906d704209a89c852039f9eb1a5ec85
        name: my-nodejs
        resources: {}
status: {}
